//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssetMaintenanceEntities : DbContext
    {
        public AssetMaintenanceEntities()
            : base("name=AssetMaintenanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GFI_AMM_AssetExtProVehicles> GFI_AMM_AssetExtProVehicles { get; set; }
        public virtual DbSet<GFI_AMM_MaintenanceTrip> GFI_AMM_MaintenanceTrip { get; set; }
        public virtual DbSet<GFI_AMM_VehicleMaintCat> GFI_AMM_VehicleMaintCat { get; set; }
        public virtual DbSet<GFI_AMM_VehicleMaintenance> GFI_AMM_VehicleMaintenance { get; set; }
        public virtual DbSet<GFI_AMM_VehicleMaintItems> GFI_AMM_VehicleMaintItems { get; set; }
        public virtual DbSet<GFI_AMM_VehicleMaintStatus> GFI_AMM_VehicleMaintStatus { get; set; }
        public virtual DbSet<GFI_AMM_VehicleMaintTypes> GFI_AMM_VehicleMaintTypes { get; set; }
        public virtual DbSet<GFI_AMM_VehicleMaintTypesLink> GFI_AMM_VehicleMaintTypesLink { get; set; }
        public virtual DbSet<GFI_AMM_VehicleTypes> GFI_AMM_VehicleTypes { get; set; }
        public virtual DbSet<GFI_FLT_Asset> GFI_FLT_Asset { get; set; }
        public virtual DbSet<GFI_FLT_AssetDataType> GFI_FLT_AssetDataType { get; set; }
        public virtual DbSet<GFI_FLT_AssetDeviceMap> GFI_FLT_AssetDeviceMap { get; set; }
        public virtual DbSet<GFI_FLT_AssetExt> GFI_FLT_AssetExt { get; set; }
        public virtual DbSet<GFI_FLT_AssetTypeMapping> GFI_FLT_AssetTypeMapping { get; set; }
        public virtual DbSet<GFI_FLT_AssetUOM> GFI_FLT_AssetUOM { get; set; }
        public virtual DbSet<GFI_FLT_ExtTripInfo> GFI_FLT_ExtTripInfo { get; set; }
        public virtual DbSet<GFI_FLT_RoadSpeedType> GFI_FLT_RoadSpeedType { get; set; }
        public virtual DbSet<GFI_SYS_LookUpTypes> GFI_SYS_LookUpTypes { get; set; }
        public virtual DbSet<GFI_SYS_LookUpValues> GFI_SYS_LookUpValues { get; set; }
        public virtual DbSet<GFI_SYS_User> GFI_SYS_User { get; set; }
        public virtual DbSet<GFI_DieselDetail> GFI_DieselDetail { get; set; }
        public virtual DbSet<GFI_GasolineDetail> GFI_GasolineDetail { get; set; }
        public virtual DbSet<GFI_FuelDetail> GFI_FuelDetail { get; set; }
        public virtual DbSet<FuelRecord_Detail> FuelRecord_Detail { get; set; }
        public virtual DbSet<Fuel_Record> Fuel_Record { get; set; }
    }
}
