//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetMaintenaceType
    {
        public int AssetMaintenceId { get; set; }
        public int AssetId { get; set; }
        public int MaintenceId { get; set; }
    
        public virtual GFI_AMM_VehicleMaintTypes GFI_AMM_VehicleMaintTypes { get; set; }
        public virtual GFI_FLT_Asset GFI_FLT_Asset { get; set; }
    }
}
