//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel_Record
    {
        public int Id { get; set; }
        public string FillingStation { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<decimal> FuelInvoice { get; set; }
        public int BatchNo { get; set; }
        public decimal RetailPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
