//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelRecord_Detail
    {
        public long FuelRecord_DetailId { get; set; }
        public int FuelRecordId { get; set; }
        public System.DateTime Date { get; set; }
        public string VoucherNo { get; set; }
        public string RegistrationNo { get; set; }
        public string FillingStation { get; set; }
        public string Driver { get; set; }
        public string FuelType { get; set; }
        public int Quantities { get; set; }
        public Nullable<int> ActualMilage { get; set; }
        public Nullable<int> CurrentMilage { get; set; }
        public Nullable<double> AmountExVal { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> VatAmount { get; set; }
        public double AmountInVal { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public long CreatedOn { get; set; }
        public bool Active { get; set; }
    
        public virtual Fuel_Record Fuel_Record { get; set; }
    }
}
