//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel_Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fuel_Record()
        {
            this.FuelRecord_Detail = new HashSet<FuelRecord_Detail>();
        }
    
        public int Id { get; set; }
        public string FillingStation { get; set; }
        public Nullable<System.DateTime> PeriodTo { get; set; }
        public Nullable<System.DateTime> PeriodFrom { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<decimal> FuelInvoice { get; set; }
        public int BatchNo { get; set; }
        public decimal RetailPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuelRecord_Detail> FuelRecord_Detail { get; set; }
    }
}
