//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFI_FLT_RoadSpeedType
    {
        public int iID { get; set; }
        public string VehicleType { get; set; }
        public Nullable<int> MotorWay { get; set; }
        public Nullable<int> RoadA { get; set; }
        public Nullable<int> RoadB { get; set; }
        public Nullable<int> RoadC { get; set; }
        public Nullable<int> RoadD { get; set; }
        public Nullable<int> RoadE { get; set; }
        public Nullable<int> RoadF { get; set; }
        public Nullable<int> RoadG { get; set; }
        public Nullable<int> RoadH { get; set; }
    }
}
