//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFI_AMM_VehicleMaintTypes
    {
        public int MaintTypeId { get; set; }
        public Nullable<int> MaintCatId_cbo { get; set; }
        public string Description { get; set; }
        public Nullable<int> OccurrenceType { get; set; }
        public Nullable<System.DateTime> OccurrenceFixedDate { get; set; }
        public Nullable<int> OccurrenceFixedDateTh { get; set; }
        public Nullable<int> OccurrenceDuration { get; set; }
        public Nullable<int> OccurrenceDurationTh { get; set; }
        public string OccurrencePeriod_cbo { get; set; }
        public Nullable<int> OccurrenceKM { get; set; }
        public Nullable<int> OccurrenceKMTh { get; set; }
        public Nullable<int> OccurrenceEngineHrs { get; set; }
        public Nullable<int> OccurrenceEngineHrsTh { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
