//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFI_FLT_ExtTripInfo
    {
        public int IID { get; set; }
        public string ExtTripID { get; set; }
        public string Field1Value { get; set; }
        public string Field2Value { get; set; }
        public string Field3Value { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AssetName { get; set; }
        public string Field4Value { get; set; }
        public string Field5Value { get; set; }
        public string Field6Value { get; set; }
        public string AdditionalField1 { get; set; }
        public string AdditionalField2 { get; set; }
        public string AdditionalValue1 { get; set; }
        public string AdditionalValue2 { get; set; }
        public Nullable<int> Field1Name { get; set; }
        public Nullable<int> Field2Name { get; set; }
        public Nullable<int> Field3Name { get; set; }
        public Nullable<int> Field4Name { get; set; }
        public Nullable<int> Field5Name { get; set; }
        public Nullable<int> Field6Name { get; set; }
        public Nullable<double> Consumption { get; set; }
        public Nullable<double> Timediff { get; set; }
        public Nullable<System.DateTime> DateTimeGPSStart_UTC { get; set; }
        public Nullable<System.DateTime> DateTimeGPSStop_UTC { get; set; }
        public Nullable<double> TripDistance { get; set; }
    }
}
