//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFI_FLT_AssetUOM
    {
        public int iID { get; set; }
        public int AssetID { get; set; }
        public int UOM { get; set; }
        public Nullable<int> Capacity { get; set; }
    }
}
