//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFI_FLT_AssetExt
    {
        public int AssetId { get; set; }
        public Nullable<int> MakeID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> YearManufactured { get; set; }
        public Nullable<System.DateTime> PurchasedDate { get; set; }
        public Nullable<decimal> PurchasedValue { get; set; }
        public string RefA { get; set; }
        public string RefB { get; set; }
        public string RefC { get; set; }
        public string RefD { get; set; }
        public string ExternalRef { get; set; }
        public string EngineSerialNumber { get; set; }
        public Nullable<int> EngineCapacity { get; set; }
        public Nullable<int> EnginePower { get; set; }
    }
}
