//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFI_SYS_User
    {
        public int UID { get; set; }
        public string Username { get; set; }
        public string Names { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public string Status_b { get; set; }
        public string Password { get; set; }
        public string AccessList { get; set; }
        public string StoreUnit_b { get; set; }
        public string UType_cbo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Dummy1 { get; set; }
        public int LoginCount { get; set; }
        public Nullable<int> AccessTemplateId { get; set; }
        public int LoginAttempt { get; set; }
        public string PreviousPassword { get; set; }
        public Nullable<System.DateTime> PasswordUpdateddate { get; set; }
        public int MaxDayMail { get; set; }
        public int UsrTypeID { get; set; }
        public string UsrTypeDesc { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> PlnLkpVal { get; set; }
        public Nullable<int> MobileAccess { get; set; }
        public Nullable<int> ExternalAccess { get; set; }
        public string TwoStepVerif { get; set; }
        public Nullable<int> TwoStepAttempts { get; set; }
        public System.Guid UserToken { get; set; }
        public Nullable<System.DateTime> PswdExpiryDate { get; set; }
        public Nullable<System.DateTime> PswdExpiryWarnDate { get; set; }
        public string LastName { get; set; }
    }
}
