//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMaintenance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFI_FLT_Asset
    {
        public int AssetID { get; set; }
        public string AssetNumber { get; set; }
        public string Status_b { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string TimeZoneID { get; set; }
        public int Odometer { get; set; }
        public string AssetName { get; set; }
        public int AssetType { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> RoadSpeedType { get; set; }
    
        public virtual GFI_AMM_AssetExtProVehicles GFI_AMM_AssetExtProVehicles { get; set; }
    }
}
